VEDIC_COMMAND = {
    "name": "vedic",
    "description": "Sidereal (Lahiri) positions of the Ascendant and the Hindu Navagraha.",
    "options": [
        {
            "name": "year",
            "description": "Year of birth (e.g. 1990)",
            "type": 4,
            "required": True,
        },
        {
            "name": "month",
            "description": "Month of birth (1–12)",
            "type": 4,
            "required": True,
            "min_value": 1,
            "max_value": 12,
        },
        {
            "name": "day",
            "description": "Day of birth (1–31)",
            "type": 4,
            "required": True,
            "min_value": 1,
            "max_value": 31,
        },
        {
            "name": "hour",
            "description": "Hour of birth, 24h (0–23)",
            "type": 4,
            "required": True,
            "min_value": 0,
            "max_value": 23,
        },
        {
            "name": "minute",
            "description": "Minute of birth (0–59)",
            "type": 4,
            "required": True,
            "min_value": 0,
            "max_value": 59,
        },
        {
            "name": "city",
            "description": "Birth city, e.g. Mumbai. Always shown in the result and used for the timezone.",
            "type": 3,
            "required": True,
        },
        {
            "name": "latitude",
            "description": "Optional: override the city's latitude for precise calculations (e.g. 19.0760).",
            "type": 10,
            "required": False,
            "min_value": -90,
            "max_value": 90,
        },
        {
            "name": "longitude",
            "description": "Optional: override the city's longitude for precise calculations (e.g. 72.8777).",
            "type": 10,
            "required": False,
            "min_value": -180,
            "max_value": 180,
        },
        {
            "name": "timezone",
            "description": "Override the UTC offset (e.g. 5.5 or 5:30) used for the local-to-UTC conversion.",
            "type": 3,
            "required": False,
        },
        {
            "name": "chalit",
            "description": "Add Sripati (Porphyry) bhava/house placements for each graha.",
            "type": 5,
            "required": False,
        },
        {
            "name": "chart_style",
            "description": "Chart style: North Indian (diamond), South Indian (grid), or Circular (wheel). Default: North.",
            "type": 3,
            "required": False,
            "choices": [
                {"name": "North Indian", "value": "north"},
                {"name": "South Indian", "value": "south"},
                {"name": "Circular", "value": "circular"},
            ],
        },
    ],
}

COMMANDS = [VEDIC_COMMAND]
